export const COLEGIOS = {
  "2018":{
    "CANCUN MEXICO":[
      "Argentina Modelo",
      "Argentina Modelo Norte",
      "Babar",
      "Brick Towers",
      "Ceferino",
      "Chaltel",
      "Devoto",
      "Dover",
      "Glasgow",
      "Juan XXIII",
      "La Anunciata",
      "Lincoln Belgrano",
      "Lincloln Pilar",
      "Magno",
      "Marin San Isidro",
      "Norbridge",
      "North Hills",
      "Northern",
      "Palermo Chico",
      "Pio XII",
      "San Jorge Quilmes",
      "San Martín de Tours (varones)",
      "Santa María de Pilar",
      "St. Hildas",
      "St. Johns (pilar)",
      "St. Mary (pilar)",
      "St. Mathews (belgrano)",
      "United High School",
      "Washington",
      "Wellspring",
      "Godspell",
      "St. Catherines",
      "Esquiu",
      "San Marcos",
      "B.E.D.E.S.",
      "San Cirano",
      "Belgrano Day School",
      "St. Martin in the Fields",
      "Moorlands",
      "San Xavier",
      "St. Brendan",
      "San Jorge Norte",
    ],
    "CERRO CATEDRAL":[
      "San Esteban",
      "San Felipe",
      "Pilgrims San Isidro",
      "Jesús María Reconquista",
      "St. Pauls (Pergamino)",
      "La Unidad",
      "La Salle de Rosario",
      "Santa Maria de Pehuajo",
      "Cardenal Copello",
      "Pilgrims Pacheco",
      "San Antonio De Areco",
      "Los Robles Centro",
      "Escuela del Alba (Lincoln)",
      "Old Christians (Uruguay)",
      "St Patricks (Uruguay)",
      "Las Martas",
    ],
    "INTERCOLEGIAL CHAPELCO":[
      "St.Edward's",
      "St.Brendan's"
    ]
  },
  "2017":{
    "CANCUN MEXICO":[
      "Antonio Berni",
      "San Martin De Tours Mujeres",
      "Sworn Belgrano",
      "St., Johns Pilar",
      "Lincoln (Belgrano)",
      "Norbridge (Pilar)",
      "North Hills (Pilar)",
      "Moorlands",
      "St Johns Beccar",
      "Godspell",
      "St. Hilda",
      "Belgrano Day School",
      "St Brendan",
      "BrickTowers",
      "St Matthews (Pilar)",
      "St Martin In The Fields",
      "San Marcos",
      "St Mary Pilar",
      "St. Edwards",
      "St. Matthews Belgrano",
      "Lincoln Pilar",
      "Palermo Chico",
      "Wellspring Bedes",
      "St Paul´s",
      "Southern Cross",
      "Esquiu",
      "Nightingale",
      "San Nicolás",
      "St Catherines",
    ],
    "CERRO CATEDRAL":[
      "San Esteban",
      "San Felipe",
      "Pilgrims San Isidro",
      "Jesús María Reconquista",
      "St. Pauls (Pergamino) ",
      "La Unidad",
      "La Salle de Rosario",
      "Santa Maria de Pehuajo",
      "Cardenal Copello",
      "Pilgrims Pacheco",
      "San Antonio De Areco",
      "Los Robles Centro",
      "Escuela del Alba (Lincoln)",
      "Old Christians (Uruguay)",
      "St Patricks (Uruguay)",
      "Las Martas",
    ],
    "INTERCOLEGIAL CHAPELCO":[
      "St.Edward's",
      "St.Brendan's"
    ]
  },
  "2016":{
    "CANCUN MEXICO":[
      "San Jorge (Mendoza)",
      "St. Johns Pilar",
      "Lincoln (Belgrano)",
      "Norbridge (Pilar)",
      "North Hills (Pilar)",
      "Moorlands",
      "St. Johns Beccar",
      "Godspell",
      "Santa Rosa",
      "St. Hilda",
      "Belgrano Day School",
      "St Brendan",
      "Brick Towers",
      "St. Matthews (Pilar)",
      "Northlands Nordelta",
      "San Marcos",
      "St Mary Pilar",
      "Marin",
      "Huerto de los Olivos",
      "Fatima",
      "St. Paul´s",
    ],
    "CERRO CATEDRAL":[
      "San Felipe",
      "Pilgrims San Isidro",
      "Jesús María Reconquista",
      "St. Pauls (Pergamino)",
      "La Unidad„ Las Marías",
      "La Salle de Rosario",
      "Santa Maria de Pehuajo",
      "Cardenal Copello",
      "PiIgrims Pacheco",
      "San Antonio De Areco",
      "Los Robles Centro",
      "Escuela del Alba (Lincoln)",
      "Jesus Maria (Recoleta)",
      "British (uruguay)",
      "Extra British Old Christians (Uruguay)",
      "St Patricks (Uruguay)",

    ],
    "INTERCOLEGIAL CHAPELCO":[
      "St.Edward's",
      "St.Brendan's"
    ]
  },
  "2015":{
    "CANCUN MEXICO":[
      "San Andrés",
      "San Patricio",
      "WoodLand Bayard",
      "Lincoln (Belgrano)",
      "Lincoln (Pilar)",
      "San Jorge Norte",
      "North Hills Moorlands",
      "St. Johns Pilar",
      "St. Johns Beccar",
      "Godspell",
      "Santa Rosa",
      "San Jorge (Mendoza)",
      "St Belgrano Day School",
      "St Brendan's Palermo Chico",
      "Sworn Belgrano",
      "BrickTowers",
    ],
    "CERRO CATEDRAL":[
      "San Felipe",
      "Pilgrims San Isidro",
      "Jesús María Reconquista",
      "Santa Ines",
      "St. Pauls (Pergamino)",
      "La Unidad",
      "La Salle de Rosario",
      "Santa Maria de Pehuajo",
      "Santa Teresa (Tigre)",
      "Cardenal Copello",
      "Santo Tomás de Aquino",
      "Pilgrims Pacheco",
      "San Antonio De Areco",
      "Adoratrices",
      "Los Robles Pilar",
      "Escuela del Alba (Lincoln)",
      "Juan XXIII British (uruguay)",
      "Extra British Old Christians (Uruguay)",
      "St Patricks (Uruguay)",
      "Las Manías",
    ],
    "INTERCOLEGIAL CHAPELCO":[
      "St. Edward's",
      "St. Brendan's"
    ]
  },
  "2014":{
    "CANCUN MEXICO":[
      "Icei (Mendoza)",
      "Espa)ol (Mendoza)",
      "San Marcos (San Isidro)",
      "Huerto de los Olivos",
      "Babar (Don Torcuato)",
      "San Mateo Olivos",
      "San Nicolás (Mendoza)",
      "San Andrés (Mendoza)",
    ],
    "CERRO CATEDRAL":[
      "San Felipe",
      "Pilgrims San Isidro",
      "Jesús María Reconquista",
      "Santa Irles",
      "St. Pauls (Pergamino)",
      "La Unidad„ Las Marías",
      "La Salle de Rosario",
      "Santa Maria de Pehuajo",
      "Santa Teresa (Tigre)",
      "Cardenal Copello",
      "Antonio Berni",
      "Pilgrims Pacheco",
      "San Antonio De Areco",
      "Adoratrices",
      "San Mateo",
      "St. Mary Of The Hills",
      "Los Robles (Pilar)",
      "Escuela del Alba (Lincoln)",
      "Juan XXIII",
      "British (Uruguay)",
      "Extra British. Old Christians (Uruguay)",
      "St Patricks (Uruguay)",
    ],
    "INTERCOLEGIAL CHAPELCO":[
      "St.Edward's",
      "St.Brendan's",
    ]
  },
  "2013":{
    "CANCUN MEXICO":[
      "San Andres",
      "St. Johns Pilar",
      "St. Johns Beccar",
      "Macnab Bernal",
      "Maristas",
      "Babar Don Torcuato",
    ],
    "CERRO CATEDRAL":[
      "San Felipe",
      "Pilgrims San Isidro",
      "Jesús María Reconquista",
      "Santa Ines",
      "St. Pauls (Pergamino)",
      "La Unidad",
      "Las Marías",
      "La Salle de Rosario",
      "Santa Maria de Pehuajo",
      "Santa Teresa (Tigre)",
      "Cardenal Copello",
      "Antonio Berni",
      "Pilgrims Pacheco",
      "San Antonio De Areco",
      "Adoratrices",
      "San Mateo",
      "St Mary Of The Hills",
      "Los Robles Pilar",
      "Escuela del Alba",
      "Nuevo Las Lomas",
      "British (Uruguay)",
      "Extra British. Old Christians (Uruguay)",
      "St Patricks (Uruguay)",
    ],
    "INTERCOLEGIAL CHAPELCO":[
      "St. Edward's",
      "St. Brendan's",

    ],
    "PORTO SEGURO - BRASIL":[
      "Goethe Schule",
      "Estrada",
      "San Patricio",
      "WoodLand",
    ]
  },
  "2012":{
    "CANCUN MEXICO":[
"San Andres",
"San Patricio",
"WoodLand",
    ],
    "CERRO CATEDRAL":[
      "Michael Ham",
      "San Felipe",
      "Pilgrims San Isidro",
      "Jesús María Reconquista",
      "Santa Ines",
      "St. Pauls (Pergamino) ",
      "La Unidad",
      "Almafuerte",
      "Las Marías",
      "La Salle de Rosario",
      "Santa Maria de Pehuajo",
      "Santa Teresa (Tigre)",
      "Cardenal Copello",
      "Holly Cross",
      "Pilgrims Pacheco",
      "San Antonio De Areco",
      "British (uruguay)",
      "Extra British. Old Christians (Uruguay)",
      "St Patricks (Uruguay)",
    ],
    "INTERCOLEGIAL CHAPELCO":[
      "St.Edward's",
      "St.Brendan's",
    ],
    "PORTO SEGURO - BRASIL":[
      "Los Robles (Pilar)",
      "San Rarnon",
      "Liceo Francés",
      "Misericordia Rosario",
      "Estrada Babar",
      "Manuel Belgrano",
      "Macnab Bernal",
      "Maristas",
      "Goethe Schule",
      "Ireland College",
    ]
  },
  "2011":{
    "CANCUN MEXICO":[
      "San Marcos",
      "Christian Andersen de Pacheco",
      "Babar."
    ],
    "CERRO CATEDRAL":[
      "Los Robles Centro",
      "San Felipe",
      "Pilgrims",
      "Jesús María Reconquista",
      "Santa Ines",
      "St. Pauls (Pergamino)",
      "La Unidad",
      "Misericordia",
      "Almafuerte",
      "Sworn (Pacheco)",
      "Las Marías",
      "La Salle de Rosario",
      "Santa Maria de Pehuajo",
      "Santa Teresa (Tigre)",
      "Adoratrices British (uruguay)",
      "Extra British. Old Christians (Uruguay)",
      "St Patricks (uruguay)",
    ],
    "INTERCOLEGIAL CHAPELCO":[
      "St.Edward's",
      "St.Brendan's",
    ],
    "PORTO SEGURO - BRASIL":[
      "Los Robles (Pilar)",
      "Liceo Francés",
      "Misericordia Rosario",
      "Arrayanes y Mannab Bernal",
      "Maristas",
      "Goethe Schule",
      "Ireland College",
    ]
  },
  "2010":{
    "CANCUN MEXICO":[
      "Lincoln",
      "San Andrés",
      "Babar",
      "Riverside",
      "Maristas",
    ],
    "CERRO CATEDRAL":[
      "Los Robles Centro",
      "San Felipe",
      "Jesús María Reconquista",
      "Santa Inés",
      "La Salle Centro",
      "St. Pauls (Pergamino)",
      "La Unidad",
      "Santa Teresa Palermo",
      "Michael Ham",
      "Misericordia",
      "Mallinckrodt Martínez",
      "Almafuerte",
      "Sworn (Pacheco)",
      "Las Manías",
      "Santa Teresa (Tigre)",
      "St Trinians",
      "San Tarsicio",
      "Adoratrices",
      "British (uruguay)",
      "Extra British. Old Christians (Uruguay)",
      "Pilgrims",
    ],
    "INTERCOLEGIAL CHAPELCO":[
      "St.Edward's",
      "St.Brendan's",
    ],
    "PORTO SEGURO - BRASIL":[
      "Los Robles (Pilar)",
      "Liceo Francés",
      "Goethe Schule",
      "Ireland College",
      "Misericordia Rosario",
    ]
  },
  "2009":{
    "CANCUN MEXICO":[
      "Lincoln",
      "Maristas",
    ],
    "CERRO CATEDRAL":[

    ],
    "INTERCOLEGIAL CHAPELCO":[
      "San Marcos",
      "San Andres",
      "Belgrano Day School",
      "St Johns (Pilar)",
      "Liceo Francés",
      "Goethe Schule",
      "Escuela del Sol",
      "Macnal Bernal",
      "Ireland College",
    ],
    "PORTO SEGURO - BRASIL":[
      "Los Robles",
      "San Felipe",
      "Pilgrims",
      "Jesús María",
      "Santa Ines",
      "Washington",
      "St. Pauls (Pergamino)",
      "La Unidad",
      "St. Mary of the Hills",
      "Misericordia",
      "La Anunciata",
      "Sworn (Pacheco)",
      "Las Manías Santa Teresa (Tigre)",
      "St.Trinians",
      "San Tarsicio",
      "British (Uruguay)",
      "Old Christians (Uruguay)",
      "St Patricks (Uruguay)",
    ]
  },
  // ' '  ( (  ) ) ..
   "2008":{
    "CANCUN MEXICO":[
      "San Andres",
      "San Marcos",
      "St Nilda 's",
      "Florence Nightingale",
      "Washington",
      "Don Bosco",
      "San Jorge Quilmes",
    ],
    "CERRO CATEDRAL":[
      "San Felipe",
      "San Lucas",
      "Estrada",
      "Perito Moreno",
      "La Salle",
      "Aberdare",
      "Santa Teresa de Palermo",
      "Babar",
      "Jesús Maria",
      "Santos Padres",
      "San Tarcisio",
      "St. Trinneans",
      "Cardenal Copello",
      "La Paz",
      "Martin y Omar",
      "San Miguel",
      "La Unidad",
      "Santa Teresa de Tigre",
      "Las Ma)as",
      "Jesús María de BV",
      "San Martín de Tours",
      "Labarden",
      "San Esteban",
      "St.Edward's",
      "British (Uruguay)",
      "Woodland (Uruguay)",
      "St Patricks (Uruguay)",
      "Old Christian (Uruguay)",
      "St.Mary of the Hillls",
      "Pilgrims",
    ],
    "CHAPELCO":[
      "Sworn",
      "St. Brendan's",
      "St. Edward's",
    ],
    "PORTO SEGURO - BRASIL":[
      "Goethe Schule",
      "Lincoln",
    ],
    "PUCON CHILE":[
      "Santa Ines",
      "Pergamino",
    ]
  },
  "2007":{
    "CERRO CATEDRAL":[
      "San Nicolás",
      "San Felipe",
      "Moorlands",
      "St.Mary of the Hills",
      "San Martín de Tours (Hombres)",
      "Los Robles de Pilar",
      "Santos Padres",
      "San Marcelo",
      "Jesus Maria (Centro)",
      "Sta.Teresa (Tigre)",
      "St. Edward's",
      "San Juan Precursor",
      "British (Uruguay)",
      "Woodland (Uruguay)",
      "St Patricks (Uruguay)",
      "Adoratrices",
      "Las Marías",
      "San Pablo (Pergamino)",
      "Jesús María de B.Vista",
      "San Luis",
      "La Unidad",
      "St Catherine's",
      "Babar",
      "Mallinckrodt (Centro.)",
      "Pueblo Blanco",
      "San Tarcisio",
      "Sworn de Pacheco",
      "E. Blue Bell",
      "Los Padres (Venado Tuerto)",
      "Santa Ines",
      "St. Brendan's",
    ],
    "CHAPELCO":[
      "St. Brendan´s",
      "Sworn (Pacheco)",
      "San Eduardo",
    ],
    "PORTO SEGURO - BRASIL":[
      "San Andrés",
    ]
  },
  "2006":{
    "CERRO CATEDRAL":[
      "San Nicolás",
      "Santa Ines",
      "San Felipe",
      "St.Brendan's",
      "Michael Ham",
      "Pilgrim's",
      "St. Mary of the Hills",
      "San Martin de Tours (Hombres)",
      "San Martin de Tours (Mujeres)",
      "La Unidad",
      "St Trinnean Jesus Maria",
      "Sta.Teresa (Tigre)",
      "St.Edward's",
      "San Juan Precursor",
      "San Esteban British (Uruguay)",
      "Santa Ethnea",
      "Los Naranjos",
      "Adoratrices",
      "Las Marías",
      "San Pablo (Pergamino)",
      "Jesús Maria de B.Vista",
      "San Luis",
      "La Unidad",
      "Malleincrodt (Miz.)",
      "Pueblo Blanco",
      "Bayard",
      "North Hin",
      "E. Blue Bell",
      "Los Padres (Venado Tuerto)",
      "Santos Padres",
    ],
    "PORTO SEGURO - BRAZIL":[
      "San Andrés",
    ],
    "CHAPELCO":[
      "San Eduardo",
      "St. Brendan’s",
    ]
  },
  "2005":{
    "CERRO CATEDRAL":[
      "San Agustin",
      "San Nicolas",
      "Santa Mes",
      "San Felipe",
      "San Lucas",
      "Moorlands",
      "St.Brendans",
      "Pilgrims",
      "St.Mary of the Hills",
      "San Martín de Tours (Hombres)",
      "San Martin de Tours (Mujeres)",
      "La Unidad",
      "St Trinnean’s",
      "Jesus Maria",
      "Sta.Teresa (Tigre)",
      "San Juan Precursor",
      "San Esteban",
      "San Tarcicio",
      "Chaltel",
      "Santa Ethnea",
      "San Luis",
      "San Mateo de Olivos",
      "Malinckroft (Martinez)",
      "Los Robles",
      "Malinckrodt (Centro)",
      "Santos Padres",
      "British (Uruguay)",
    ],
    "PORTO SEGURO - BRAZIL":[
      "St. John's",
    ],
    "CHAPELCO":[
      "San Eduardo",
      "St. Brendan’s",
    ]
  },
  "2004":{
    "CERRO CATEDRAL":[
      "Santa Irles",
      "Pilgrims",
      "St.Mary of the Hills",
      "San Martín de Tours (Hombres)",
      "San Martín de Tours (Mujeres)",
      "La Unidad",
      "San Felipe",
      "St. Trinnean's",
      "St. Brendans",
      "San Nicolas",
      "Jesus Maria",
      "Sta. Teresa (Tigre)",
      "San Marcelo",
      "St. Edwards",
      "Moorlands",
      "Misericordia",
      "Sagrada Familia",
      "Santos Padres",
      "San Lucas",
    ],
    "PORTO SEGURO - BRAZIL":[
      "B.E.D.E.S.",
      "San Andrés",
    ],
    "CHAPELCO":[
      "St. Brendan’s",
      "St. Eduard’s",
    ],
    "PRAIA DO ROSA BRAZIL":[
      "Estrada",
    ]
  },
  "2003":{
    "CERRO CATEDRAL":[
      "San Lucas",
      "San Nicolás",
      "San Juan el Precursor",
      "La Salle",
      "Santo Tomás de Aquino",
      "St. Trinnean’s",
      "San Martín de Tours (Hombre)",
      "Labarden",
      "Santa María de Pehuajó",
      "Jesús María",
      "St. Mary of the Hills",
      "San Felipe",
      "North Hills",
      "San Martín de Tours (Mujeres)",
      "Pilgrims",
      "San isidro Labrador",
      "Moorlands",
      "Santos Padres",
      "Babar",
      "Chaltel",
      "San Miguel",
      "Sta. Teresa",
      "British (Uruguay)",
      "San Gregorio",
      "Estrada",
      "San Marcelo",
      "Nacional de Bs. As.",
      "Piaget",
      "La Unidad",
      "Los Alerces",
    ],
    "PORTO SEGURO - BRAZIL":[
      "St. John’s",
    ],
    "CHAPELCO":[
      "St. Brendan’s",
      "St. Eduard’s",
    ],
    "PRAIA DO ROSA - BRAZIL":[
      "Goethe Schule",
      "San Felipe",
    ]
  },
  "2002":{
    "CERRO CATEDRAL":[
      "San Lucas",
      "San Nicolás",
      "San Juan el Precursor",
      "La Salle",
      "Santo Tomás de Aquino",
      "St. Trinnean’s",
      "San Martín de Tours (Hombres)",
      "Labarden",
      "Santa María de Pehuajó",
      "Jesús María",
      "St. Mary of the Hills",
      "San Felipe",
      "North Hills",
      "San Martín de Tours (Mujeres)",
      "Pilgrims",
      "San Isidro Labrador",
      "Moorlands",
      "Santos Padres",
      "Babar",
      "Chaltel",
      "San Miguel",
      "Sta. Teresa",
      "Britis (Uruguay)",
      "San Gregorio",
      "Estrada",
      "San Marcelo",
      "Nacional de Bs. As.",
      "Piaget",
      "La Unidad",
      "Los Alerces",

    ],
    "CHAPELCO":[
      "St. Brendan’s",
      "St. Edward’s",
    ]
  },
  "2001":{
    "CERRO CATEDRAL":[
      "San Lucas",
      "San Agustín",
      "St. Brendan’s",
      "Don Jaime",
      "Las Marías",
      "Santa María",
      "Pilgrims",
      "Santa Teresa Tigre",
      "St. Mary of the Hills",
      "San Juan el Precursor",
      "Santa Ethnea",
      "La Unidad",
      "La Salle",
      "Santos Padres",
      "Extra British",
      "Michael Ham",
      "Santa María de Luján",
      "Southern Cross",
      "Piaget",
      "Martín y Omar",
    ],
    "PORTO SEGURO - BRAZIL":[
      "San Martín de Tours (Mujeres)",
      "San Marcos",
      "San Felipe",
      "Goethe Shule",
    ],
    "CHAPELCO":[
      "San Eduardo",
      "St. Brendan’s",
    ]
  },
}
